from __future__ import annotations

import logging
import os
import time

from google import genai
from google.genai import types

logger = logging.getLogger("medical_ai.llm")

DISCLAIMER = (
    "This report was generated by an AI system for informational and workflow-support "
    "purposes only. It is NOT a medical diagnosis. All findings must be reviewed and "
    "confirmed by a licensed radiologist or physician before any clinical decision is made."
)

SYSTEM_PROMPT = SYSTEM_PROMPT = """
You are an AI-assisted radiology reporting assistant designed to generate preliminary draft reports for chest X-ray examinations. Your role is to support, but never replace, the clinical judgment of a licensed radiologist.

You will receive:
- The model's predicted class (NORMAL or PNEUMONIA)
- The model confidence score
- The complete class probability distribution
- A brief description of the lung regions highlighted by the Grad-CAM heatmap

Generate a concise, professional report using the following sections:

1. AI Impression
- If the prediction is PNEUMONIA, use cautious language such as:
  "The AI model identifies imaging features that may be suggestive of pneumonia."
- If the prediction is NORMAL, state:
  "The AI model does not identify obvious radiographic features suggestive of pneumonia."
- Never describe the prediction as a confirmed diagnosis.

2. Key Observations
- Summarize the Grad-CAM highlighted regions.
- Reference only the information provided.
- Do not fabricate radiographic findings or anatomical abnormalities.
- Use 2–4 concise bullet points.

3. Confidence & Limitations
- State the model confidence percentage.
- Explain that this represents an automated first-pass AI assessment.
- Mention that model performance is dependent on the training dataset.
- State that subtle, atypical, or overlapping pathologies may not be detected.
- Emphasize that clinical correlation and expert radiologist review are essential.

4. Suggested Next Steps
- Recommend review by a qualified radiologist.
- Recommend correlation with clinical history, physical examination, and laboratory findings.
- If clinically indicated, recommend additional imaging or follow-up evaluation.

Writing Style:
- Professional radiology reporting language.
- Objective, concise, and evidence-based.
- Maximum 800 words.
- Avoid absolute statements.
- Never provide treatment recommendations.
- Never fabricate findings beyond the supplied information.
- Clearly communicate diagnostic uncertainty where appropriate.
"""

DEFAULT_MODEL = "gemini-2.5-flash" 


def _describe_gradcam_region(predicted_class: str) -> str:
    """
    Placeholder heuristic description of Grad-CAM focus.
    A production system would derive this from actual heatmap centroid/quadrant
    analysis (see app/ml/gradcam.py) rather than a static string.
    """
    if predicted_class == "PNEUMONIA":
        return "increased activation concentrated in the lower and mid lung zones, consistent with regions where pneumonic infiltrates are commonly assessed"
    return "diffuse, low-intensity activation without strong focal concentration in any single lung zone"


class ReportGenerator:
    def __init__(self, api_key: str | None = None, model: str | None = None):
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY")
        
        self.model = model or os.environ.get("GEMINI_MODEL", DEFAULT_MODEL)

        if not self.api_key:
            logger.warning(
                "GEMINI_API_KEY not found in environment. ReportGenerator will use the "
                "deterministic fallback template for every request until this is set."
            )
            self.client = None
        else:
            self.client = genai.Client(api_key=self.api_key)
            logger.info(
                "ReportGenerator initialized with Gemini model '%s' (key ends in ...%s).",
                self.model,
                self.api_key[-4:],
            )

    def generate_report(
        self,
        predicted_class: str,
        confidence: float,
        class_probabilities: dict,
        gradcam_region_hint: str | None = None,
    ) -> str:
        if not self.client:
            logger.warning("generate_report called with no client configured -- using fallback.")
            return self._fallback_report(predicted_class, confidence, class_probabilities)

        region_desc = gradcam_region_hint or _describe_gradcam_region(predicted_class)

        user_prompt = f"""Model prediction: {predicted_class}
Confidence: {confidence:.2%}
Full class probabilities: {class_probabilities}
Grad-CAM region description: {region_desc}"""

        # Transient server-side errors (503 model overloaded, 429 rate limit)
        # are common with any hosted LLM API, especially newly-launched models
        # under launch-week traffic. Retry a few times with exponential
        
        max_attempts = 3
        last_exc: Exception | None = None

        for attempt in range(1, max_attempts + 1):
            try:
                response = self.client.models.generate_content(
                    model=self.model,
                    contents=user_prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=SYSTEM_PROMPT,
                        temperature=0.3,
                        max_output_tokens=1000,
                    ),
                )
                return f"{response.text.strip()}\n\n---\n{DISCLAIMER}"
            except Exception as exc:
                last_exc = exc
                is_transient = "503" in str(exc) or "UNAVAILABLE" in str(exc) or "429" in str(exc) or "RESOURCE_EXHAUSTED" in str(exc)
                if is_transient and attempt < max_attempts:
                    wait_s = 2 ** attempt  # 2s, 4s, 8s
                    logger.warning(
                        "Gemini call failed (attempt %d/%d, transient=%s): %s -- retrying in %ds",
                        attempt, max_attempts, is_transient, exc, wait_s,
                    )
                    time.sleep(wait_s)
                    continue
                break

        # All retries exhausted (or a non-transient error) -- fall back.
        logger.exception("Gemini API call failed after retries; falling back to template report.")
        body = self._fallback_report(predicted_class, confidence, class_probabilities)
        body += f"\n\n[Note: LLM call failed after {max_attempts} attempts, showing template report. Error: {type(last_exc).__name__}: {last_exc}]"
        return f"{body}\n\n---\n{DISCLAIMER}"

    @staticmethod
    def _fallback_report(predicted_class: str, confidence: float, class_probabilities: dict) -> str:
        """Deterministic template used if no GEMINI_API_KEY is configured or the call fails."""
        region_desc = _describe_gradcam_region(predicted_class)
        return (
            f"AI Impression: Findings are suggestive of {predicted_class.title()}.\n\n"
            f"Key Observations:\n"
            f"- Model confidence for {predicted_class}: {confidence:.2%}\n"
            f"- Grad-CAM shows {region_desc}.\n\n"
            f"Confidence & Limitations: This is an automated first-pass classification "
            f"({class_probabilities}). It may miss atypical presentations and does not "
            f"replace clinical correlation.\n\n"
            f"Suggested Next Steps: Clinical correlation and physician review recommended."
        )


_generator_instance: ReportGenerator | None = None


def get_report_generator() -> ReportGenerator:
    global _generator_instance
    if _generator_instance is None:
        _generator_instance = ReportGenerator()
    return _generator_instance

